### ISSUE TITLE
Use cast via void * instead of memcpy?

### ISSUE THREAD

**Issue by aslakrin** [eddelbuettel/RcppInt64#2] opened 2024-02-06 08:11 UTC
Hi,

I was facing the same problem as you and had a look at this package among other things for inspiration.

What I ended up doing however was to, in my c++ function, just cast the input/output numeric vector to uint64_t via void. At least for me this avoided reinterpret cast warning, and also avoids function call overhead to memcpy (I assume).

Eg

```c
NumericVector foo(const NumericVector bar) {
  uint64_t *u64bar = (uint64_t *)((void *)&bar[0]));

  NumericVector ret(bar.size());
  ret.attr("class") = "integer64";
  uint64_t *u64ret = (uint64_t *)((void *)&ret[0]));

  for(ssize_t i = 0; i < bar.size(); ++i) u64ret[i] = u64bar[i] * 2;

  return ret;
}
```

Is there a reason why memcpy is preferred to this method in this library?

**Comment by eddelbuettel** [comment] 2024-02-06 11:41
I do not understand your question, can you try to rephrase what you tried to do / what you did / what you encountered?
What problem did you try to solve?

Also, are you aware of R's `bit64` package and exactly how it implements providing `int64_t` semantics by storing its bit-by-bit representation in a `double`, the 64-bit datatype that R offers?  That is why we `memcpy`.

See e.g. https://gallery.rcpp.org/articles/creating-integer64-and-nanotime-vectors/ for some background and illustration.

**Comment by aslakrin** [comment] 2024-02-06 12:05
Hi @eddelbuettel, sorry for being unclear.

It seems to me that since double and uint64 are both occupying the same amount of space, an array of 8 * 100 bytes should be viewable as either. That is to say, the compiler should be able to treat the memory as if it were an array of u64.

Using memcpy achieves the same thing more or less, but it can only operate inefficiently on either one row at a time, where the inefficiency stems from calling memcpy, or on a vector at a time, where the inefficiency would stem from having to represent the vector twice, as an array of u64 and an array of double (NumericVector).

On the other hand, since we know that given a numeric vector `NumericVector bar` of size whatever, the memory at `bar[0]` and `size*sizeof(double)` bytes hence is a contiguous block of memory that it should be possible to trick the compiler into viewing as an array of uint64 directly, without involving memcpy. And this is possible if you first erase the type by casting to void pointer, and then to whatever you want.

So we have

```c
// A regular vector
NumericVector bar(100, 0);

// Reinterpret cast, but via the low road
uint64_t *u64bar = (uint64_t *)((void *)&bar[0]));

// Efficient, presumably, memory access into the u64 array
u64bar[13] = 0x8b283082800bfff;
```

This is what I show in the code example, and my question is, given that this to me seems more efficient than involving memcpy, is there some to me uknown reason that this is unsafe or for some reason not preferable

**Comment by eddelbuettel** [comment] 2024-02-06 12:55
`double` is native type for R, and that is what it is used here.

The `memcpy` is used on purpose to transfer the _bitwise content_ of a vector of `int64_t` into a vector of `double`.  That is what the package does.  I don't think you have shown a defect in the package per its scope.  I appreciate that you took the time to explain the issue, even twice, but I think what you are concerned with is not a concern there.

See this:

```r
> suppressMessages({library(bit64); library(Rcpp)})      # bit64 loads with 'noise'
> Rcpp::cppFunction("NumericVector val() { std::vector<int64_t> v{42, 84}; return toInteger64(v); }", depends="RcppInt64", include="#include <RcppInt64>")
> val()
integer64
[1] 42 84
> 
```

We have two `int64_t` values in the C++ body.  By using `toInteger64()`, which uses `memcpy`, we get a vector of `double` _with the `int64` payload_ that is then accessed in R as `int64` -- and the desired `int64_t` payload is available to us in R -- thanks to the `bit64` package.  My `RcppInt64`  helps with the conversion.

I am going to close this.  If you can provide similar functionality without the `memcpy` I would be all ears and encourage you to show it with an example.  But I fear there is possible misunderstanding here about what is done and why which I hoped to clarify.  If I missed the topic, let me know.  The package still works as intended.

**Closed as completed** 2024-02-06 12:59 UTC

**Comment by aslakrin** [comment] 2024-02-09 13:06
I am clearly a bit bad at communicating here. My background is in pure C more so than R or even C++ so I do understand that there is a NumericVector which is actually a bunch of doubles standing on each others' shoulders and that this same memory is hijacked and we pretend it's actually a long integer. I also understand that `toInteger64` works exactly as advertised and does it well.

However my point is that there are severe performance penalties involved with using memcpy.

First of all, every input vector to C++ code is essentially duplicated in memory since fromInteger64 creates a new vector of int64_t and calls memcpy to convert.

Second of all, which isn't a big problem when you duplicate the entire vector and call memcpy just once, there is also a performance penalty from calling memcpy. That penalty is incurred instead if you want to save memory and use memcpy to convert and work on each row instead of duplicatng the vector.

Since I have to deal with large and several input columns I can't afford to create a new int64 vector and copy into it.

Instead therefore my solution for my problem is to replace `fromInteger64` with 

```c++
/* Assume an integer64 object already is allocated */
static inline uint64_t *NumericVector_as_uint64_t(NumericVector vec) {
    return (uint64_t *)((void *)vec.begin());
}
```

This function doesn't do anything in terms of computation or memory, it just provides the compiler with a symbol that it thinks is an array of 64 bit integers, in my case unsigned.

I also made a convenience function to create a new NumericVector in case one is needed for a return value:

```c++
/* Allocate an integer64 object */
static inline NumericVector Integer64(size_t size) {
    NumericVector n(size);
    n.attr("class") = "integer64";
    return n;
}
```

But this is neither here nor there. The point is that for the example function in the repository, it becomes:

```c++
Rcpp::NumericVector Int64toInt64(Rcpp::NumericVector vec) {
    NumericVector ret = Integer64(vec.size());
    uint64_t *vec64 = NumericVector_as_uint64_t(vec);
    uint64_t *ret64 = NumericVector_as_uint64_t(ret);

    for (size_t i = 0; i < ret.size(); ++i) {
        ret64[i] = vec64[i];
        // Rcpp::Rcout << ++ret64[i] << std::endl;
    }
    return ret;
}
```

In this example there is only one input vector, so only that peak memory is saved, and an output vector is still needed, but you can see that this reduction in peak memory allocation only becomes more pronounced the more input vectors are needed.

For your reference I also did a benchmark, and found I had to use bench_process_memory() to capture memory that was only allocated and freed inside of C++. There is probably a better way, because here I have to restart R to reset the high usage watermark.

```R
library(tidyverse)
library(bit64)

bench::bench_process_memory()

a <- 1:150e7 |> as.integer64()  # around 11Gb
# b <- 1:150e7 |> as.integer64()
# c <- 1:150e7 |> as.integer64()

bench::bench_process_memory()

# First allocation of b, call gc() often to remove noise in allocations
gc(); b <- Int64toInt64cast(a); gc(); bench::bench_process_memory()

# Second allocation of b, gc() is needed to drop the old one, peak increases by one output vector
gc(); b <- Int64toInt64cast(a); gc(); bench::bench_process_memory()

# Repeat same but with original function, observe peak now grows with size of input since it double allocates
gc(); b <- Int64toInt64(a); gc(); bench::bench_process_memory()
```

To summarize, I think people who need to work on large vectors in C++ space would benefit from not double-allocating the input.

Also, with increased number of input vectors also comes increase in overhead just related to copying. If you consider an alternative toy example:

```c++
// [[Rcpp::export]]
Rcpp::NumericVector Int64sum(Rcpp::NumericVector vec0, Rcpp::NumericVector vec1, Rcpp::NumericVector vec2) {
    std::vector<int64_t> nvec0 = fromInteger64(vec0);
    std::vector<int64_t> nvec1 = fromInteger64(vec1);
    std::vector<int64_t> nvec2 = fromInteger64(vec2);
    uint64_t sum = 0;
    for (size_t i = 0; i < vec0.size(); ++i) {
        sum += nvec0[i] + nvec1[i] + nvec2[i];
    }

    return toInteger64(sum);
}
```
And a version that just casts

```c++
// [[Rcpp::export]]
Rcpp::NumericVector Int64sumcast(Rcpp::NumericVector vec0, Rcpp::NumericVector vec1, Rcpp::NumericVector vec2) {
    NumericVector ret = Integer64(1);
    uint64_t *vec064 = NumericVector_as_uint64_t(vec0);
    uint64_t *vec164 = NumericVector_as_uint64_t(vec1);
    uint64_t *vec264 = NumericVector_as_uint64_t(vec2);
    uint64_t *ret64 = NumericVector_as_uint64_t(ret);

    *ret64 = 0;

    for (size_t i = 0; i < vec0.size(); ++i) {
        *ret64 += vec064[i] + vec164[i] + vec264[i];
    }
    return ret;
}
```

You can observe with `bench` that the casting version uses no additional memory, and is also 4x faster. Which none of those considerations are necessarily applicable to the use-case you or any of the consumers of this package care about, but at least now I hope I've explained in some more detail what I meant :)

**Comment by eddelbuettel** [comment] 2024-02-09 13:21
I think we are talking past each other and I am equally bad at explaining. 

Do you understand that the memory I copy via `memcpy` is not accessed in C / C++ directly _but handed back to R in the 'simple container class' `integer64` of the `bit64` package_ where it is accessed.  The package `bit64` only uses an `int64_t`.  It uses `memcpy`.  I am playing along _by its rules_.

You still have not shown a round trip.  What matters is the following.

```r
> library(bit64)
> Rcpp::cppFunction("NumericVector doubleMe(NumericVector nv) { std::vector<int64_t> iv = fromInteger64(nv); for (auto& x: iv) x = 2*x; return toInteger64(iv); }", depends="RcppInt64", include="#include <RcppInt64>")
> v <- as.integer64(c(1e0, 1e3, 1e6, 1e9, 1e12))
> v
integer64
[1] 1             1000          1000000       1000000000    1000000000000
> doubleMe(v)
integer64
[1] 2             2000          2000000       2000000000    2000000000000
> 
```

I do not see how _switching from `int64_t` that `bit64` works with to a different `uint64_t` with what I suspect is a different payload_ can work.  I have not doubt that your casts are faster.  But I think they corrupt the values.

**Comment by eddelbuettel** [comment] 2024-02-09 13:35
But I read too fast.  Your example works.  Now ... I am confused as to why it does. This rattles a few assumptions I had for a few years of working with this (where I generally relied on `memcpy` and often with large enough vectors to matter.

Slighlty mod'ed example of yours in one file (easier to work with):

```c++

#include <RcppInt64>

// [[Rcpp::depends(RcppInt64)]]

/* Assume an integer64 object already is allocated */
static inline uint64_t *NumericVector_as_uint64_t(Rcpp::NumericVector vec) {
    return (uint64_t *)((void *)vec.begin());
}

/* Allocate an integer64 object */
static inline Rcpp::NumericVector Integer64(size_t size) {
    Rcpp::NumericVector n(size);
    n.attr("class") = "integer64";
    return n;
}

// [[Rcpp::export]]
Rcpp::NumericVector Int64toInt64timesTwoPlusOne(Rcpp::NumericVector vec) {
    Rcpp::NumericVector ret = Integer64(vec.size());
    uint64_t *vec64 = NumericVector_as_uint64_t(vec);
    uint64_t *ret64 = NumericVector_as_uint64_t(ret);

    for (size_t i = 0; i < ret.size(); ++i) {
        ret64[i] = vec64[i] * 2 + 1;
        // Rcpp::Rcout << ++ret64[i] << std::endl;
    }
    return ret;
}


/*** R
v <- as.integer64(c(1e0, 1e3, 1e6, 1e9, 1e12, 1e15, 1e18))
v
Int64toInt64timesTwoPlusOne(v)
***/
```

which does what it claims to do over the range of values we care about:

```r
> Rcpp::sourceCpp("~/git/rcppint64/issue2.cpp")

> v <- as.integer64(c(1e0, 1e3, 1e6, 1e9, 1e12, 1e15, 1e18))

> v
integer64
[1] 1                   1000                1000000             1000000000          1000000000000      
[6] 1000000000000000    1000000000000000000

> Int64toInt64timesTwoPlusOne(v)
integer64
[1] 3                   2001                2000001             2000000001          2000000000001      
[6] 2000000000000001    2000000000000000001
> 
```

**Comment by eddelbuettel** [comment] 2024-02-09 13:47
What about the other case I also care about:  Receive a vector of `integer64` values from R, turn them into `std::vector<int64_t>` and work with them in C++?  The `uint64_t` does not help there.  And I sometimes need that chunk of memory to pass an actual vector around.  I do not yet see how not copying could help there.

The `Int64toInt64timesTwoPlusOne()` works because we (on purpose) do not materialize the vector.  What if we need to pass an actual `std::vector<int64_t>` to another (independent, third-party) function?

**Comment by aslakrin** [comment] 2024-02-10 11:10
The ugly cast works for the same reason that memcpy works, it coerces the data to be of a specific type and disregards any type information or other c++ based magic. With memcpy you do it by copying raw data into a memory region viewed as `(u)int64_t` already, with the cast we create a new view onto the same existing region via a new symbol. Memcpy assumes the data exists in a contiguous region and so does the array cast.

For any operation where you don't need to shrink or grow a vector, either just take the input NumVec and cast it, or pre-allocate a NumericVector and manipulate via the pointer to the data. It will work to do push_back or other rezise operations on the NumVec if needed, but perhaps you then need to cast again since the data buffer pointed to by `begin()` might have moved to another heap block.

But if as you say you need to pass another function an actual vector then I think you have to copy as before. I don't see a way of wrapping a second vector object around the first one's data although knowing C++ it's probably not impossible.

**Comment by eddelbuettel** [comment] 2024-02-10 12:17
Correct. Construction of an actual `std::vector<int64_t>` (for use by other C++ parts) from the `NumericVector` requires a copy, also because other components do not know about R's lifetime management and the object may disappear.

What you pointed out is entirely try for _local 'vistor-style' patterns_ where only want to access the payload.  In that sense the round-turn example of 'times two' is a perfect example for such a visitor.  We could add another helper function, and / or add another demo doing what you suggested.

**Comment by aslakrin** [comment] 2024-02-10 14:01
I don't know if it's possible for a numeric vector to disappear while you're in a call stack with that vector as input. I haven't seen this documented but it would be insanity if an input parameter could become invalid while calling a secondary function. It would require really bad multi threaded code and not be a problem isolated to rcpp. So i would not hesitate passing the cursed pointer along to other functions in the same thread and in the same invocation, either to your own functions, or library functions that happen to accept these arrays. The backing object that owns the data won't go away while in the blocking rcpp function.

I'm not sure what visitor style pattern is, but you can, in your own code, both mutate the data as int64 via the data cast, and perform vector operations on the backing object.

I'm sure you knew all this but just wanted to clarify since we've talked so much at cross purposes already.

Have a good weekend!
